name: tracktable
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - tracktable
  - ipykernel
  - pandoc
  - sphinx
  - pip:
    - breathe
    - nbsphinx
    - nbsphinx-link
